services:
  app:
    image: mcr.microsoft.com/devcontainers/python:3-3.14-trixie
    volumes:
      - ..:/workspaces:cached
    # Keep the container running so VS Code can attach to it.
    command: sleep infinity
    environment:
      - TEST_MONGODB_URI=mongodb://root:localDevelopmentRootPassword@mongodb:27017/?replicaSet=rs0&authSource=admin
      - MONGODB_URI=mongodb://root:localDevelopmentRootPassword@mongodb:27017/?replicaSet=rs0&authSource=admin
    networks:
      - app-network
    depends_on:
      - mongodb

  mongodb:
    image: bitnami/mongodb:latest
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=localDevelopmentRootPassword
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_REPLICA_SET_KEY=localDevelopmentKey
      - MONGODB_ADVERTISED_HOSTNAME=mongodb  
    volumes:
      - mongodb-data-rs0:/bitnami/mongodb
    networks:
      - app-network

volumes:
  mongodb-data-rs0:

networks:
  app-network:
    driver: bridge
