openapi: 3.0.0
info:
  title: 0xEG7 Shorten URL API
  description: API documentation for the Shorten URL project. This API allows users to create shortened URLs for long URLs, making them easier to share and manage.
  version: 1.0.0
servers:
  - url: https://apis.0x1115.com/shorten/v1
    description: Production server
paths:
  /shorten:
    post:
      summary: Shorten a URL
      description: Endpoint to create a shortened URL
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  description: The original URL to be shortened
              required:
                - url
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        
components:
  schemas:
    SuccessResponse:
      type: object
      properties:
        message:
          type: string
          description: Message response
        data:
          type: object
          description: The returned parameter
          properties:
            original_url:
              type: string
              description: The original URL
            shortened_url:
              type: string
              description: The shortened URL

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: Error message
        data:
          type: object
          description: Error message
        

