name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Essential Gadgets Bootstrap (EGB)
      run: /bin/bash scripts/egb/1_docker-image-build.sh

    - name: Build the Shorten URL Application
      run: /bin/bash scripts/app/shorten_url/1_docker-image-build.sh

    - name: Docker Hub login
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME_0x1115 }}
        password: ${{ secrets.DOCKERHUB_PASSWORD_0x1115 }}

    - name: Push Docker images
      run: docker push 0x1115/shorten-url:latest
